# Generated by Django 4.2.5 on 2024-02-22 20:59

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/user.jpg', null=True, upload_to=users.models.CustomUser.image_upload_to),
        ),
    ]
