# Generated by Django 5.0.2 on 2024-02-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_event_slug_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.TextField(default='Short description', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='Title', max_length=100),
        ),
    ]
