# Generated by Django 5.0.2 on 2024-02-19 20:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_event_slug_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
