# Generated by Django 5.0.2 on 2024-02-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_event_description_alter_news_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
