# Generated by Django 4.2.5 on 2024-02-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_event_slug_alter_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(default='news/default.png', upload_to='news/'),
        ),
    ]
