# Generated by Django 4.2.5 on 2024-02-20 18:51

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_news_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='short_description',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Content', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(default='Short description', max_length=100),
        ),
    ]
