# Generated by Django 4.2.5 on 2024-03-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
    ]
