# Generated by Django 4.2.5 on 2024-03-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_end_reservation_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
