# Generated by Django 4.2.5 on 2024-04-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservation_results_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
